export * from "./api/Api"
export * from "./metodos/Metodoscardapio"
export * from "./metodos/Metodoscomandas"   
export * from "./metodos/Metodospedidos"
export * from "./autenticação/Login"
export * from "./autenticação/Buscardados"
